hide all
show sticks, all
show cartoon, all
set cartoon_ring_mode
set cartoon_tube_radius, .3
hide all
color green, resi 17-18 or resi 28-29
color green, resi 13-15 or resi 31-33
color green, resi 32-28
color green, resi 19-12
hide cartoon, resi 42
hide sticks, resi 42
hide cartoon, resi 43
hide sticks, resi 43
hide cartoon, resi 44
hide sticks, resi 44
hide cartoon, resi 45
hide sticks, resi 45
hide cartoon, resi 46
hide sticks, resi 46
hide cartoon, resi 47
hide sticks, resi 47
hide sticks, resi 55
hide cartoon, resi 55
hide sticks, resi 56
hide cartoon, resi 56
hide sticks, resi 57
hide cartoon, resi 57
hide sticks, resi 58
hide cartoon, resi 58
hide sticks, resi 59
hide cartoon, resi 59
hide sticks, resi 60
hide cartoon, resi 60
hide cartoon, resi 17
hide sticks, resi 17
hide cartoon, resi 18
hide sticks, resi 18
hide sticks, resi 28
hide cartoon, resi 28
hide sticks, resi 29
hide cartoon, resi 29
hide cartoon, resi 13
hide sticks, resi 13
hide cartoon, resi 14
hide sticks, resi 14
hide cartoon, resi 15
hide sticks, resi 15
hide sticks, resi 31
hide cartoon, resi 31
hide sticks, resi 32
hide cartoon, resi 32
hide sticks, resi 33
hide cartoon, resi 33
hide cartoon, resi 3
hide sticks, resi 3
hide cartoon, resi 4
hide sticks, resi 4
hide cartoon, resi 5
hide sticks, resi 5
hide cartoon, resi 6
hide sticks, resi 6
hide cartoon, resi 7
hide sticks, resi 7
hide cartoon, resi 8
hide sticks, resi 8
hide cartoon, resi 9
hide sticks, resi 9
hide sticks, resi 63
hide cartoon, resi 63
hide sticks, resi 64
hide cartoon, resi 64
hide sticks, resi 65
hide cartoon, resi 65
hide sticks, resi 66
hide cartoon, resi 66
hide sticks, resi 67
hide cartoon, resi 67
hide sticks, resi 68
hide cartoon, resi 68
hide sticks, resi 69
hide cartoon, resi 69
color blue, resi 34
color blue, resi 35
color blue, resi 36
color blue, resi 37
color blue, resi 38
color blue, resi 39
color blue, resi 40
color blue, resi 41
color blue, resi 48
color blue, resi 49
color blue, resi 50
color blue, resi 51
color blue, resi 52
color blue, resi 53
color blue, resi 54
color blue, resi 1
color blue, resi 2
color blue, resi 61
color blue, resi 62
color blue, resi 19
color blue, resi 20
color blue, resi 21
color blue, resi 22
color blue, resi 23
color blue, resi 24
color blue, resi 25
color blue, resi 26
color blue, resi 27
color blue, resi 10
color blue, resi 11
color blue, resi 12
color yellow, resi 30
color yellow, resi 16
color blue, resi 70
run output/1y26/pymol/coarse_grain.pym
show cartoon, temp
